name: odoo test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: odoo:12
      options: --user root
    
    
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:10
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: odoo
          POSTGRES_USER: odoo
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - name: install git
      run:  apt-get update && apt-get install -y git-all
    - uses: actions/checkout@v2
    - name: move files
      run: cp -r * /mnt/extra-addons
    - name: run test
      run: python3 test_server.py
